#!/usr/bin/env python

'''
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

fibonacci_old = 1 # the implicit previous term is 1

index     = 0
fibonacci = 1

the_sum   = 0

while fibonacci <= 4000000:
  # Note that every third term in the Fibonacci sequence *must* be even, and others *must* be odd.
  if index % 3 == 1:
    the_sum += fibonacci

  fibonacci_new = fibonacci + fibonacci_old

  fibonacci_old = fibonacci
  fibonacci     = fibonacci_new

  index += 1

print(the_sum)